ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "VT-40-2"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.Heat = true
ENT.CamOffset = Vector(3.9, 0, 3.5)
ENT.RotorBone = 2
ENT.RotorPitch = true
ENT.DroneModel = "models/vt40/2vt40krtz_zcfix.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 12
ENT.MaxVel = 1400
ENT.Mass = 16
ENT.Thrust = 1000
ENT.TurnRate = 150
ENT.HoverForce = 1.04
ENT.CollideDetonate = 150
ENT.SignalRangeMul = 3