ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "Mavic 2"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = false
ENT.Stable = true
ENT.SignalRangeMul = 16
ENT.DropPayload = true
ENT.IconOverride = "entities/sw_mavic2.png"
ENT.DroneModel = "models/sw/avia/mavic2/mavic2.mdl"
ENT.ModelScale = 2
ENT.IdleSound = "sw/mavic2/mavic2_idle.wav"
ENT.MaxHP = 100
ENT.MaxVel = 1700
ENT.Mass = 10
ENT.Thrust = 850
ENT.TurnRate = 150
ENT.HoverForce = 1.04
ENT.CollideBreak = 400
