ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_crocus"
ENT.PrintName = "Crocus Frag"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.IconOverride = "entities/sw_crocus_tbg7.png"
ENT.DroneModel = "models/sw/avia/crocus/crocus_tbg7.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 5
ENT.MaxVel = 2700
ENT.Mass = 7
ENT.Thrust = 1200
ENT.TurnRate = 210
ENT.HoverForce = 1.08
ENT.CollideDetonate = 180
