ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "VT-40"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.Heat = true
ENT.CamOffset = Vector(2, 0, 5.5)
ENT.RotorBone = 1
ENT.RotorPitch = true
ENT.DroneModel = "models/vt40/vt40krtz.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 8
ENT.MaxVel = 1600
ENT.Mass = 8
ENT.Thrust = 1100
ENT.TurnRate = 190
ENT.HoverForce = 1.06
ENT.CollideDetonate = 170
ENT.SignalRangeMul = 3
