ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "KVN-2"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.Fiber = true
ENT.CamFOV = 54
ENT.CamOffset = Vector(9, 0, 5.1)
ENT.RotorBone = 1
ENT.RotorPitch = true
ENT.DroneModel = "models/sw/avia/kvn/kvn2.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 8
ENT.MaxVel = 1250
ENT.Mass = 12
ENT.Thrust = 900
ENT.TurnRate = 140
ENT.HoverForce = 1.04
ENT.CollideDetonate = 150
ENT.SignalRangeMul = 8
