ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "KVN-3"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.Heat = true
ENT.Fiber = true
ENT.CamFOV = 90
ENT.CamOffset = Vector(11.5, 0, 5.10)
ENT.RotorBone = 1
ENT.RotorPitch = true
ENT.DroneModel = "models/sw/avia/kvn/kvn3.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 8
ENT.MaxVel = 1400
ENT.Mass = 9
ENT.Thrust = 980
ENT.TurnRate = 165
ENT.HoverForce = 1.05
ENT.CollideDetonate = 160
ENT.SignalRangeMul = 10
