ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "Crocus"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = false
ENT.DroneModel = "models/sw/avia/crocus/crocus.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 40
ENT.MaxVel = 1750
ENT.Mass = 4
ENT.Thrust = 1400
ENT.TurnRate = 250
ENT.HoverForce = 1.12
ENT.CollideBreak = 450
ENT.SignalRangeMul = 4
