ENT.Type = "anim"
ENT.Base = "ent_zc_fpv_base"
ENT.PrintName = "Crocus PG-7"
ENT.Category = "ZCity FPV"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.ZCFpvDrone = true
ENT.Strike = true
ENT.LiveCharge = true
ENT.Heat = true
ENT.IconOverride = "entities/sw_crocus_pg7.png"
ENT.DroneModel = "models/sw/avia/crocus/crocus_pg7.mdl"
ENT.IdleSound = "sw/crocus/crocus_idle.wav"
ENT.MaxHP = 5
ENT.MaxVel = 2800
ENT.Mass = 6
ENT.Thrust = 1200
ENT.TurnRate = 220
ENT.HoverForce = 1.08
ENT.CollideDetonate = 180
